services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongo"
      MONGO_INITDB_ROOT_PASSWORD: "mongo"
    restart: always

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongo

  c-v2x-rsu:
    build: ../C-V2X-RSU
    depends_on:
      - rabbitmq
    restart: always

  c-v2x-backend:
    build: ../C-V2X-Backend
    ports:
      - "5000:5000"
      - "3426:3426"
    depends_on:
      - rabbitmq
      - mongo
    restart: always

  c-v2x-obu:
    build:
      context: ../C-V2X-Fleet-Backend
      dockerfile: Dockerfile.obu
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq
      - c-v2x-rsu
      - c-v2x-backend

  c-v2x-car-frontend:
    build: ../C-V2X-Car-Frontend
    depends_on:
      - c-v2x-obu
      - c-v2x-backend
    ports:
      - "3000:3000"

  c-v2x-control-center:
    build: ../C-V2X-Frontend
    depends_on:
      - c-v2x-backend
    ports:
      - "3002:3000"
