services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongo"
      MONGO_INITDB_ROOT_PASSWORD: "mongo"
    restart: always

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongo

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"  # MQTT default port
      - "9001:9001"  # WebSocket port (optional)
    volumes:
      - ./mosquitto/config:/mosquitto/config  # Place your custom mosquitto.conf here
      - ./mosquitto/data:/mosquitto/data      # Persistent storage for MQTT messages
      - ./mosquitto/log:/mosquitto/log        # Logs directory

  c-v2x-rsu:
    build: ../C-V2X-RSU
    environment:
      RABBITMQ_URL: amqp://rabbitmq:rabbitmq@rabbitmq:5672
      RSU_IDENTIFIER: 62261a65d66c6be0a63c051f
      RSU_PORT: 5111
      RSU_LATITUDE: 37.7749
      RSU_LONGITUDE: -122.4194
    ports:
      - "5111:5111"
    depends_on:
      - rabbitmq
      - mosquitto
    restart: always

  c-v2x-backend:
    build: ../C-V2X-Backend
    environment:
      MONGO_URI: mongodb://mongo:mongo@mongo:27017/cv2x?authSource=admin
      APP_PORT: 5000
      SOCKET_PORT: 3426
      RABBITMQ_HOST: amqp://rabbitmq:rabbitmq@rabbitmq:5672
      JWT_SECRET: thisisasecret
      JWT_COOKIE_EXPIRE: 1
      JWT_EXPIRE: 1d
      NODE_ENV: development
      INFLUXDB_HOST: http://influxdb:8086/
      INFLUXDB_BUCKET: mybucket
      INFLUXDB_ORG: myorg
      INFLUXDB_TOKEN: mytoken
    ports:
      - "5000:5000"
      - "3426:3426"
    depends_on:
      - rabbitmq
      - mongo
    restart: always

  c-v2x-obu:
    build:
      context: ../C-V2X-Fleet-Backend
      dockerfile: Dockerfile.obu
    environment:
      RABBITMQ_URL: amqp://rabbitmq:rabbitmq@rabbitmq:5672
      OBU_SOCKET_PORT: 8001
      CAR_IDENTIFIER: 5b360fdea392d731829ded18
      MECH_SOCKET_PORT: 8000
      MECH_CLIENT_SOCKET_PORT: 12000
      NEXT_PUBLIC_WEB_SOCKET_URL: ws://c-v2x-backend:3426/
      RSU_ADDRESS: c-v2x-rsu
      RSU_PORT: 5111
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq
      - c-v2x-rsu
      - c-v2x-backend
      - mosquitto

  # c-v2x-car-frontend:
  #   build:
  #     context: ../C-V2X-Car-Frontend
  #     args:
  #       NEXT_PUBLIC_API_URL: http://localhost:5000/api
  #       # NEXT_PUBLIC_GOOGLE_MAPS_API_KEY:
  #       NEXT_PUBLIC_WEB_SOCKET_URL: ws://localhost:3426/
  #       NEXT_PUBLIC_API_CAM_URI: http://localhost:3426
  #       NEXT_PUBLIC_API_SERVER_URI: http://localhost:5000/
  #       NEXT_PUBLIC_OBU_SOCKET_WS_URL: ws://localhost:8001/
  #       NEXT_PUBLIC_OBU_SOCKET_HTTP_URL: http://localhost:8001
  #       NEXT_PUBLIC_CAR_ID: 5b360fdea392d731829ded18
  #       NEXT_PUBLIC_CAM_FRONT: 5b360fdea392d731829ded19
  #       NEXT_PUBLIC_CAM_BACK: 2
  #       NEXT_PUBLIC_CAM_LEFT: 3
  #       NEXT_PUBLIC_CAM_RIGHT: 4
  #       NEXT_PUBLIC_CAM_START_WITH: 0
  #       NEXT_PUBLIC_DRIVER_USERNAME: driverUser1
  #       NEXT_PUBLIC_DRIVER_PASSWORD: password
  #   depends_on:
  #     - c-v2x-obu
  #     - c-v2x-backend
  #     - preview-dedicated-server
  #     - preview-thumbnail-server
  #     # - rtsp-server
  #   ports:
  #     - "3000:3000"

  c-v2x-control-center:
    build:
      context: ../C-V2X-Frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:5000/api
        NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: AIzaSyBQ0kAFrCwxD21vFiKeCgj-d-lVnrmojzc
        NEXT_PUBLIC_WEB_SOCKET_URL: ws://localhost:3426/
    depends_on:
      - c-v2x-backend
    ports:
      - "3002:3000"

  c-v2x-reporter:
    build: ../C-V2X-Reporter
    ports:
      - "8002:80"

  # rtsp-to-webrtc:
  #   build: ../RTSPtoWebRTC
  #   network_mode: host

  influxdb:
    image: influxdb:2
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: myorg
      DOCKER_INFLUXDB_INIT_BUCKET: mybucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: mytoken
      DOCKER_INFLUXDB_INIT_MODE: setup
    volumes:
      - influxdb_data:/var/lib/influxdb2
  preview-dedicated-server:
    build: ../C-V2X-Preview/dedicatedServer
    ports:
      - "8081:8081"
  preview-thumbnail-server:
    build: ../C-V2X-Preview/thumbnailServer
    ports:
      - "8080:8080"

  rtsp-server:
    image: bluenviron/mediamtx
    container_name: rtsp-server
    restart: always
    ports:
      - "8554:8554" # RTSP port
    environment:
      - RTSP_PROTOCOLS=tcp

volumes:
  influxdb_data:
